"""initial schema

Revision ID: 08edcecd8a91
Revises: 
Create Date: 2026-06-10 18:10:20.214174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08edcecd8a91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cr_by', sa.String(length=255), nullable=True),
    sa.Column('up_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('up_by', sa.String(length=255), nullable=True),
    sa.Column('del_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('del_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email_otp', sa.String(length=10), nullable=True),
    sa.Column('email_otp_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image', sa.JSON(), nullable=True),
    sa.Column('reset_token', sa.String(length=1024), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cr_by', sa.String(length=255), nullable=True),
    sa.Column('up_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('up_by', sa.String(length=255), nullable=True),
    sa.Column('del_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('del_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rooms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('max_loops', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cr_by', sa.String(length=255), nullable=True),
    sa.Column('up_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('up_by', sa.String(length=255), nullable=True),
    sa.Column('del_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('del_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_loop', sa.Integer(), nullable=True),
    sa.Column('remaining_time', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cr_by', sa.String(length=255), nullable=True),
    sa.Column('up_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('up_by', sa.String(length=255), nullable=True),
    sa.Column('del_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('del_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completion_time', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cr_by', sa.String(length=255), nullable=True),
    sa.Column('up_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('up_by', sa.String(length=255), nullable=True),
    sa.Column('del_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('del_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_items',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_category', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cr_by', sa.String(length=255), nullable=True),
    sa.Column('up_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('up_by', sa.String(length=255), nullable=True),
    sa.Column('del_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('del_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_objects',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('object_code', sa.String(length=100), nullable=True),
    sa.Column('object_name', sa.String(length=255), nullable=True),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.Column('position_x', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('position_y', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('position_z', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_interactable', sa.Boolean(), nullable=True),
    sa.Column('object_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cr_by', sa.String(length=255), nullable=True),
    sa.Column('up_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('up_by', sa.String(length=255), nullable=True),
    sa.Column('del_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('del_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_inventory',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cr_by', sa.String(length=255), nullable=True),
    sa.Column('up_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('up_by', sa.String(length=255), nullable=True),
    sa.Column('del_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('del_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['room_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puzzles',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.Column('answer_type', sa.String(length=50), nullable=True),
    sa.Column('hint_1', sa.Text(), nullable=True),
    sa.Column('hint_2', sa.Text(), nullable=True),
    sa.Column('hint_3', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('reward_item_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cr_by', sa.String(length=255), nullable=True),
    sa.Column('up_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('up_by', sa.String(length=255), nullable=True),
    sa.Column('del_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('del_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reward_item_id'], ['room_items.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_progress',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cr_by', sa.String(length=255), nullable=True),
    sa.Column('up_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('up_by', sa.String(length=255), nullable=True),
    sa.Column('del_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('del_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puzzle_dependency',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('parent_puzzle_id', sa.Integer(), nullable=False),
    sa.Column('child_puzzle_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cr_by', sa.String(length=255), nullable=True),
    sa.Column('up_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('up_by', sa.String(length=255), nullable=True),
    sa.Column('del_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('del_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['child_puzzle_id'], ['puzzles.id'], ),
    sa.ForeignKeyConstraint(['parent_puzzle_id'], ['puzzles.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puzzle_dependency')
    op.drop_table('game_progress')
    op.drop_table('puzzles')
    op.drop_table('player_inventory')
    op.drop_table('room_objects')
    op.drop_table('room_items')
    op.drop_table('leaderboard')
    op.drop_table('game_sessions')
    op.drop_table('rooms')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
